# Project: Australian Market Expansion Strategy - 
## Workforce-Based Business Expansion Analytics
### Description:

Goal: explore and clean the data 
Tech: Python\
Library: panda 
Data Source: Australian Bureau of Statistics

Data:\
All groups CPI, index numbers and percentage changes.xlsx

### Library:

In [1]:
# install
# !pip install pandas openpyxl

In [2]:
import pandas as pd

### Files:

In [3]:
fileLocation = 'D:\Working Station\Career & Project\Data\laber prediction\Original Data'

In [54]:
#CPIMonthly_path = fileLocation + "\\" + "CPI_MonthlyPercentageChange.xlsx"
EmployPopulationRatial_Path = fileLocation + '\\' + 'EmploymentToPopulationRatio.csv'
EmploymentByState_NewSouthWales_Path = fileLocation + '\\'  + 'EmploymentByState_NewSouthWales.xlsx'

Read files

In [56]:
#CPI_MonthlyOriginal = pd.read_excel(CPIMonthly_path, sheet_name = "Data1")
EmployPopulationRatial_Original = pd.read_csv(EmployPopulationRatial_Path)
EmploymentByState_NewSouthWales_Original = pd.read_excel(EmploymentByState_NewSouthWales_Path, sheet_name = 'Data1')

#The following dataset is not required 
#LabourForce_CurrentOriginal = pd.read_excel(LabourForce_Path, sheet_name = "Data 1")
#LabourForce_PreviousOriginal = pd.read_excel(LabourForce_Path, sheet_name = "Data 2")

### CPI_MonthlyPath

#### Observe and Analyse the dataset

In [9]:
CPI_MonthlyPath = CPI_MonthlyOriginal.copy()
CPI_MonthlyPath.head()

,Unnamed: 0,Contribution to All groups CPI Percentage Points Change from Previous Period ; All groups CPI ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Food and non-alcoholic beverages ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Bread and cereal products ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Bread ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Cakes and biscuits ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Breakfast cereals ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Other cereal products ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Meat and seafoods ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Beef and veal ; Australia ;,...,Contribution to All groups CPI Percentage Points Change from Previous Period ; Education ; Australia ;.1,Contribution to All groups CPI Percentage Points Change from Previous Period ; Preschool and primary education ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Secondary education ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Tertiary education ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Insurance and financial services ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Insurance ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Insurance ; Australia ;.1,Contribution to All groups CPI Percentage Points Change from Previous Period ; Financial services ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Deposit and loan facilities (direct charges) ; Australia ;,Contribution to All groups CPI Percentage Points Change from Previous Period ; Other financial services ; Australia ;
0,Unit,% pts,% pts,% pts,% pts,% pts,% pts,% pts,% pts,% pts,...,% pts,% pts,% pts,% pts,% pts,% pts,% pts,% pts,% pts,% pts
1,Series Type,Original,Original,Original,Original,Original,Original,Original,Original,Original,...,Original,Original,Original,Original,Original,Original,Original,Original,Original,Original
2,Data Type,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED,...,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED,DERIVED
3,Frequency,Month,Month,Month,Month,Month,Month,Month,Month,Month,...,Month,Month,Month,Month,Month,Month,Month,Month,Month,Month
4,Collection Month,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

Observation:\
Data set type - structural data, wide data sets
Size - 30rows X 133 columns
columns- first column contains the information of each rows without a column name which suppose to be the column names, including but not limited to Unit, series type, data type, etc. From the seconde column to the last column, the column name contains the industry, including all groups, non-alcoholic beverages, bread and cereal product, etc. 
Data types - the data sets contain categorical, numerical and datetime datasets

#### Data processing plan

Step1 - transfer the wide data to long.\
Step2 - extract the industries info and name the column industry.\
Step3 - extract the Month and Year information from the datetime (located in the first row originally), named as Month and Year.\
Step4 - deleted the columns/information that is not neceessary, for example colleciton month, series start, etc.\

#### Step1 - transfer the wide data to long.

In [10]:
CPT_Wide = CPI_MonthlyPath.T

#### Step2 - extract the industries info and name the column industry.

In [11]:
CPT_Wide.head()

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
Unnamed: 0,Unit,Series Type,Data Type,Frequency,Collection Month,Series Start,Series End,No. Obs,Series ID,2024-05-01 00:00:00,...,2025-04-01 00:00:00,2025-05-01 00:00:00,2025-06-01 00:00:00,2025-07-01 00:00:00,2025-08-01 00:00:00,2025-09-01 00:00:00,2025-10-01 00:00:00,2025-11-01 00:00:00,2025-12-01 00:00:00,2026-01-01 00:00:00
Contribution to All groups CPI Percentage Points Change from Previous Period ; All groups CPI ; Australia ;,% pts,Original,DERIVED,Month,1,2024-05-01 00:00:00,2026-01-01 00:00:00,21,A130393725R,-0.2307,...,0.7401,-0.493,0.1449,1.312,-0.0755,0.4484,-0.0074,0.0157,0.9639,0.352
Contribution to All groups CPI Percentage Points Change from Previous Period ; Food and non-alcoholic beverages ; Australia ;,% pts,Original,DERIVED,Month,1,2024-05-01 00:00:00,2026-01-01 00:00:00,21,A130395482V,0.0768,...,0.0676,0.0198,0.0756,0.062,0.0174,-0.0456,0.0258,0.0664,0.0661,0.0873
Contribution to All groups CPI Percentage Points Change from Previous Period ; Bread and cereal products ; Australia ;,% pts,Original,DERIVED,Month,1,2024-05-01 00:00:00,2026-01-01 00:00:00,21,A130391709C,0.0015,...,-0.0059,-0.0087,-0.0022,0.0109,0.0007,-0.0041,0.0013,0.0124,0.014,0.003
Contribution to All groups CPI Percentage Points Change from Previous Period ; Bread ; Australia ;,% pts,Original,DERIVED,Month,1,2024-05-01 00:00:00,2026-01-01 00:00:00,21,A130393207R,-0.0013,...,-0.0018,-0.0028,-0.0021,0.0007,-0.0003,-0.0005,0.0029,0.002,0.0028,0.002

In [12]:
CPT_Wide_resetIndex = CPT_Wide.reset_index()

In [13]:
CPT_Wide_resetIndex.head()

,index,0,1,2,3,4,5,6,7,8,...,20,21,22,23,24,25,26,27,28,29
0,Unnamed: 0,Unit,Series Type,Data Type,Frequency,Collection Month,Series Start,Series End,No. Obs,Series ID,...,2025-04-01 00:00:00,2025-05-01 00:00:00,2025-06-01 00:00:00,2025-07-01 00:00:00,2025-08-01 00:00:00,2025-09-01 00:00:00,2025-10-01 00:00:00,2025-11-01 00:00:00,2025-12-01 00:00:00,2026-01-01 00:00:00
1,Contribution to All groups CPI Percentage Poin...,% pts,Original,DERIVED,Month,1,2024-05-01 00:00:00,2026-01-01 00:00:00,21,A130393725R,...,0.7401,-0.493,0.1449,1.312,-0.0755,0.4484,-0.0074,0.0157,0.9639,0.352
2,Contribution to All groups CPI Percentage Poin...,% pts,Original,DERIVED,Month,1,2024-05-01 00:00:00,2026-01-01 00:00:00,21,A130395482V,...,0.0676,0.0198,0.0756,0.062,0.0174,-0.0456,0.0258,0.0664,0.0661,0.0873
3,Contribution to All groups CPI Percentage Poin...,% pts,Original,DERIVED,Month,1,2024-05-01 00:00:00,2026-01-01 00:00:00,21,A130391709C,...,-0.0059,-0.0087,-0.0022,0.0109,0.0007,-0.0041,0.0013,0.0124,0.014,0.003
4,Contribution to All groups CPI Percentage Poin...,% pts,Original,DERIVED,Month,1,2024-05-01 00:00:00,2026-01-01 00:00:00,21,A130393207R,...,-0.0018,-0.0028,-0.0021,0.0007,-0.0003,-0.0005,0.0029,0.002,0.0028,0.002

In [14]:
#make first row as column name
CPT_Wide_resetIndex.columns = CPT_Wide_resetIndex.iloc[0]
CPT_DropFirstRow = CPT_Wide_resetIndex.drop(0, axis = 0)

In [15]:
#name the first column industry
firstColumnName = CPT_DropFirstRow.columns[0]
rename = 'Industry'
CPT_rename = CPT_DropFirstRow.rename(columns = {firstColumnName:rename})

In [16]:
#reset index
CPT_Wide_resetIndex = CPT_rename.reset_index(drop=True)

In [17]:
#extract the industry
CPT_Wide_resetIndex['Industry'] = CPT_Wide_resetIndex['Industry'].str.split(' ; ', expand=True)[1]

#### Step3 - extract the Month and Year information from the datetime (located in the first row originally), named as Month and Year.

In [18]:
CPT_Wide_resetIndex.columns[10:]

Index([2024-05-01 00:00:00, 2024-06-01 00:00:00, 2024-07-01 00:00:00,
       2024-08-01 00:00:00, 2024-09-01 00:00:00, 2024-10-01 00:00:00,
       2024-11-01 00:00:00, 2024-12-01 00:00:00, 2025-01-01 00:00:00,
       2025-02-01 00:00:00, 2025-03-01 00:00:00, 2025-04-01 00:00:00,
       2025-05-01 00:00:00, 2025-06-01 00:00:00, 2025-07-01 00:00:00,
       2025-08-01 00:00:00, 2025-09-01 00:00:00, 2025-10-01 00:00:00,
       2025-11-01 00:00:00, 2025-12-01 00:00:00, 2026-01-01 00:00:00],
      dtype='object', name=0)

In [19]:
#Get the columns that are not CPT with dates
CPT_nonDateColumnNames = CPT_Wide_resetIndex.columns[:10].tolist()
CPT_nonDateColumnNames

['Industry',
 'Unit',
 'Series Type',
 'Data Type',
 'Frequency',
 'Collection Month',
 'Series Start',
 'Series End',
 'No. Obs',
 'Series ID']

In [20]:
#Melt the dataframe
CPT_MeltedDateTime = pd.melt(CPT_Wide_resetIndex, id_vars=CPT_nonDateColumnNames, var_name = 'DateTime', value_name = 'CPT_Changes')

In [21]:
CPT_MeltedDateTime.head()

,Industry,Unit,Series Type,Data Type,Frequency,Collection Month,Series Start,Series End,No. Obs,Series ID,DateTime,CPT_Changes
0,All groups CPI,% pts,Original,DERIVED,Month,1,2024-05-01,2026-01-01,21,A130393725R,2024-05-01,-0.2307
1,Food and non-alcoholic beverages,% pts,Original,DERIVED,Month,1,2024-05-01,2026-01-01,21,A130395482V,2024-05-01,0.0768
2,Bread and cereal products,% pts,Original,DERIVED,Month,1,2024-05-01,2026-01-01,21,A130391709C,2024-05-01,0.0015
3,Bread,% pts,Original,DERIVED,Month,1,2024-05-01,2026-01-01,21,A130393207R,2024-05-01,-0.0013
4,Cakes and biscuits,% pts,Original,DERIVED,Month,1,2024-05-01,2026-01-01,21,A130399329W,2024-05-01,0.0022

In [22]:
CPT_MeltedDateTime.dtypes

Industry                    object
Unit                        object
Series Type                 object
Data Type                   object
Frequency                   object
Collection Month            object
Series Start        datetime64[ns]
Series End          datetime64[ns]
No. Obs                     object
Series ID                   object
DateTime            datetime64[ns]
CPT_Changes                 object
dtype: object

In [23]:
CPT_MeltedDateTime['Year'] = CPT_MeltedDateTime['DateTime'].dt.year

In [24]:
CPT_MeltedDateTime['Month'] = CPT_MeltedDateTime['DateTime'].dt.month

In [25]:
CPT_MeltedDateTime.head()

,Industry,Unit,Series Type,Data Type,Frequency,Collection Month,Series Start,Series End,No. Obs,Series ID,DateTime,CPT_Changes,Year,Month
0,All groups CPI,% pts,Original,DERIVED,Month,1,2024-05-01,2026-01-01,21,A130393725R,2024-05-01,-0.2307,2024,5
1,Food and non-alcoholic beverages,% pts,Original,DERIVED,Month,1,2024-05-01,2026-01-01,21,A130395482V,2024-05-01,0.0768,2024,5
2,Bread and cereal products,% pts,Original,DERIVED,Month,1,2024-05-01,2026-01-01,21,A130391709C,2024-05-01,0.0015,2024,5
3,Bread,% pts,Original,DERIVED,Month,1,2024-05-01,2026-01-01,21,A130393207R,2024-05-01,-0.0013,2024,5
4,Cakes and biscuits,% pts,Original,DERIVED,Month,1,2024-05-01,2026-01-01,21,A130399329W,2024-05-01,0.0022,2024,5

In [26]:
CPT_MeltedDateTime.dtypes

Industry                    object
Unit                        object
Series Type                 object
Data Type                   object
Frequency                   object
Collection Month            object
Series Start        datetime64[ns]
Series End          datetime64[ns]
No. Obs                     object
Series ID                   object
DateTime            datetime64[ns]
CPT_Changes                 object
Year                         int32
Month                        int32
dtype: object

#### Step4 - deleted the columns/information that is not neceessary, for example colleciton month, series start, etc.

In [27]:
CPT = CPT_MeltedDateTime.copy()

In [28]:
CPT['No. Obs'].unique()

array([21], dtype=object)

Remove Unit, Series Type, Data Type, Frequency, Collection Month, No.Obs, because there is only one value in these columns

In [29]:
dropedColumns = ['Unit', 'Series Type', 'Data Type', 'Frequency', 'Collection Month', 'No. Obs']

In [30]:
CPT_DropedColumns = CPT.drop(columns = dropedColumns, axis = 1)

Also dropped Series Start, Series end and Series ID cause its not relavant to CPT changes. Dropped DateTime Cause we already have Year and Month

In [31]:
dropedColumns = ['Series Start', 'Series End', 'DateTime', 'Series ID']

In [32]:
CPT_DropedDates = CPT_DropedColumns.drop(columns = dropedColumns, axis = 1)

In [33]:
CPT_DropedDates.shape

(2772, 4)

In [83]:
CPT = CPT_DropedDates.copy()

### Employment to population Ration

#### Observe and Analyse the dataset

In [9]:
EmployPopulationRatial_Original

                                                             Employment-to-population ratio
NaN                                                Trend (%)        Seasonally adjusted (%)
Jan-16                                             61.4                                61.3
Feb-16                                             61.3                                61.3
Mar-16                                             61.3                                61.3
Apr-16                                             61.3                                61.2
...                                                                                     ...
Nov-25                                             63.9                                63.8
Dec-25                                             63.9                                64.0
Jan-26                                             64.0                                63.9
Large month-to-month changes occurred during th... NaN                                  NaN
Source: Australian Bureau of Statistics, Labour... NaN                                  NaN

[124 rows x 1 columns]

In [10]:
EmployPopulationRatial = EmployPopulationRatial_Original.copy()

Observation:\
The size of the data set is 124X1. The only column is named Employment-to-population ratio. Under the column there are three sub-columns. The first column is datetime, and the rest are the numerical data. The last two rows are not the value of the datasets.

#### Data processing plan

Step1 - reset index and the column names.\
Step2 - remove the last two rows.\
Step3 - extract month and year.\
Step4 - convert the datatypes of month and year to numeric.\
Step5 - convert data in seasonally adjusted from percentage to decimal

#### Step1 - reset index and the column names.

In [11]:
EmployPopulationRatial_ResetIndex = EmployPopulationRatial.reset_index()

In [12]:
EmployPopulationRatial_ResetColumnName = EmployPopulationRatial_ResetIndex.copy()
EmployPopulationRatial_ResetColumnName.columns = EmployPopulationRatial_ResetColumnName.iloc[0].tolist()
EmployPopulationRatial_ResetColumnName = EmployPopulationRatial_ResetColumnName.iloc[1:]

In [13]:
OriginalColumnNames = EmployPopulationRatial_ResetColumnName.columns
EmployPopulationRatial_ResetColumnName = EmployPopulationRatial_ResetColumnName.rename(columns = {OriginalColumnNames[0]:'Date', OriginalColumnNames[1]:'Employment_Population_Ratio', OriginalColumnNames[2]:'Ratio_SeasonallyAdjusted'})

In [14]:
EmployPopulationRatial_ResetColumnName.head()

     Date Employment_Population_Ratio Ratio_SeasonallyAdjusted
1  Jan-16                        61.4                     61.3
2  Feb-16                        61.3                     61.3
3  Mar-16                        61.3                     61.3
4  Apr-16                        61.3                     61.2
5  May-16                        61.2                     61.1

#### Step2 - remove the last two rows.

In [15]:
EmployPopulationRatial_RemovedRows = EmployPopulationRatial_ResetColumnName.iloc[:121] 
EmployPopulationRatial_RemovedRows

       Date Employment_Population_Ratio Ratio_SeasonallyAdjusted
1    Jan-16                        61.4                     61.3
2    Feb-16                        61.3                     61.3
3    Mar-16                        61.3                     61.3
4    Apr-16                        61.3                     61.2
5    May-16                        61.2                     61.1
..      ...                         ...                      ...
117  Sep-25                        64.0                     63.9
118  Oct-25                        63.9                     64.0
119  Nov-25                        63.9                     63.8
120  Dec-25                        63.9                     64.0
121  Jan-26                        64.0                     63.9

[121 rows x 3 columns]

#### Step3 - extract month and year.

In [16]:
EmployPopulationRatial_ExtractMonthYear = EmployPopulationRatial_RemovedRows.copy()

In [17]:
MonthYear = EmployPopulationRatial_ExtractMonthYear['Date'].str.split('-', expand=True)

In [18]:
MonthYear.columns

RangeIndex(start=0, stop=2, step=1)

In [19]:
EmployPopulationRatial_ExtractMonthYear['Month_Name'] = MonthYear[0]
EmployPopulationRatial_ExtractMonthYear['Year'] = '20' + MonthYear[1]

In [20]:
EmployPopulationRatial_ExtractMonthYear['Month'] = pd.to_datetime(EmployPopulationRatial_ExtractMonthYear['Month_Name'], format='%b').dt.month

In [21]:
# drop Date, Month_Name
EmployPopulationRatial = EmployPopulationRatial_ExtractMonthYear.drop(columns = ['Date', 'Month_Name'])

In [22]:
EmployPopulationRatial.head()

  Employment_Population_Ratio Ratio_SeasonallyAdjusted Year  Month
1                        61.4                     61.3   16      1
2                        61.3                     61.3   16      2
3                        61.3                     61.3   16      3
4                        61.3                     61.2   16      4
5                        61.2                     61.1   16      5

#### Step4 - convert the datatypes of month and year to numeric.

In [28]:
EmployPopulationRatial['Year'] = EmployPopulationRatial['Year'].astype(int)

1      16
2      16
3      16
4      16
5      16
       ..
117    25
118    25
119    25
120    25
121    26
Name: Year, Length: 121, dtype: int32

In [29]:
EmployPopulationRatial['Month'] = EmployPopulationRatial['Month'].astype(int)

#### Step5 - convert data in seasonally adjusted from percentage to decimal

In [33]:
#convert string to float then transfrom the data
EmployPopulationRatial['Ratio_SeasonallyAdjusted'] = EmployPopulationRatial['Ratio_SeasonallyAdjusted'].astype(float)/100

In [47]:
#drop first column
EmployPopulationRatial_cleaned = EmployPopulationRatial[['Ratio_SeasonallyAdjusted', 'Year', 'Month']]

### EmploymentByState_NewSouthWales

In [57]:
EmploymentByState_NewSouthWales_Original.head()

,Unnamed: 0,Employed total ; Persons ;,Employed total ; Persons ;.1,Employed total ; Persons ;.2,Employed total ; > Males ;,Employed total ; > Males ;.1,Employed total ; > Males ;.2,Employed total ; > Females ;,Employed total ; > Females ;.1,Employed total ; > Females ;.2,...,Participation rate ; > Males ;.2,Participation rate ; > Females ;,Participation rate ; > Females ;.1,Participation rate ; > Females ;.2,Not in the labour force (NILF) ; Persons ;,Not in the labour force (NILF) ; > Males ;,Not in the labour force (NILF) ; > Females ;,Civilian population aged 15 years and over ; Persons ;,Civilian population aged 15 years and over ; > Males ;,Civilian population aged 15 years and over ; > Females ;
0,Unit,000,000,000,000,000,000,000,000,000,...,Percent,Percent,Percent,Percent,000,000,000,000,000,000
1,Series Type,Trend,Seasonally Adjusted,Original,Trend,Seasonally Adjusted,Original,Trend,Seasonally Adjusted,Original,...,Original,Trend,Seasonally Adjusted,Original,Original,Original,Original,Original,Original,Original
2,Data Type,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,...,PERCENT,PERCENT,PERCENT,PERCENT,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK
3,Frequency,Month,Month,Month,Month,Month,Month,Month,Month,Month,...,Month,Month,Month,Month,Month,Month,Month,Month,Month,Month
4,Collection Month,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [58]:
EmploymentByState_NewSouthWales_Original.columns

Index(['Unnamed: 0', 'Employed total ;  Persons ;',
       'Employed total ;  Persons ;.1', 'Employed total ;  Persons ;.2',
       'Employed total ;  > Males ;', 'Employed total ;  > Males ;.1',
       'Employed total ;  > Males ;.2', 'Employed total ;  > Females ;',
       'Employed total ;  > Females ;.1', 'Employed total ;  > Females ;.2',
       '> Employed full-time ;  Persons ;',
       '> Employed full-time ;  Persons ;.1',
       '> Employed full-time ;  Persons ;.2',
       '> Employed full-time ;  > Males ;',
       '> Employed full-time ;  > Males ;.1',
       '> Employed full-time ;  > Males ;.2',
       '> Employed full-time ;  > Females ;',
       '> Employed full-time ;  > Females ;.1',
       '> Employed full-time ;  > Females ;.2',
       '> Employed part-time ;  Persons ;',
       '> Employed part-time ;  > Males ;',
       '> Employed part-time ;  > Females ;',
       'Employment to population ratio ;  Persons ;',
       'Employment to population ratio ;  Persons ;.1',
       'Employment to population ratio ;  Persons ;.2',
       'Employment to population ratio ;  > Males ;',
       'Employment to population ratio ;  > Males ;.1',
       'Employment to population ratio ;  > Males ;.2',
       'Employment to population ratio ;  > Females ;',
       'Employment to population ratio ;  > Females ;.1',
       'Employment to population ratio ;  > Females ;.2',
       'Unemployed total ;  Persons ;', 'Unemployed total ;  Persons ;.1',
       'Unemployed total ;  Persons ;.2', 'Unemployed total ;  > Males ;',
       'Unemployed total ;  > Males ;.1', 'Unemployed total ;  > Males ;.2',
       'Unemployed total ;  > Females ;', 'Unemployed total ;  > Females ;.1',
       'Unemployed total ;  > Females ;.2',
       '> Unemployed looked for full-time work ;  Persons ;',
       '> Unemployed looked for full-time work ;  > Males ;',
       '> Unemployed looked for full-time work ;  > Females ;',
       '> Unemployed looked for only part-time work ;  Persons ;',
       '> Unemployed looked for only part-time work ;  > Males ;',
       '> Unemployed looked for only part-time work ;  > Females ;',
       'Unemployment rate ;  Persons ;', 'Unemployment rate ;  Persons ;.1',
       'Unemployment rate ;  Persons ;.2', 'Unemployment rate ;  > Males ;',
       'Unemployment rate ;  > Males ;.1', 'Unemployment rate ;  > Males ;.2',
       'Unemployment rate ;  > Females ;',
       'Unemployment rate ;  > Females ;.1',
       'Unemployment rate ;  > Females ;.2',
       '> Unemployment rate looked for full-time work ;  Persons ;',
       '> Unemployment rate looked for full-time work ;  > Males ;',
       '> Unemployment rate looked for full-time work ;  > Females ;',
       '> Unemployment rate looked for only part-time work ;  Persons ;',
       '> Unemployment rate looked for only part-time work ;  > Males ;',
       '> Unemployment rate looked for only part-time work ;  > Females ;',
       'Labour force total ;  Persons ;', 'Labour force total ;  Persons ;.1',
       'Labour force total ;  Persons ;.2', 'Labour force total ;  > Males ;',
       'Labour force total ;  > Males ;.1',
       'Labour force total ;  > Males ;.2',
       'Labour force total ;  > Females ;',
       'Labour force total ;  > Females ;.1',
       'Labour force total ;  > Females ;.2',
       'Participation rate ;  Persons ;', 'Participation rate ;  Persons ;.1',
       'Participation rate ;  Persons ;.2', 'Participation rate ;  > Males ;',
       'Participation rate ;  > Males ;.1',
       'Participation rate ;  > Males ;.2',
       'Participation rate ;  > Females ;',
       'Participation rate ;  > Females ;.1',
       'Participation rate ;  > Females ;.2',
       'Not in the labour force (NILF) ;  Persons ;',
       'Not in the labour force (NILF) ;  > Males ;',
       'Not in the labour force (NILF) ;  > Females ;',
       'Civilian population aged 15 years and over ;  Persons ;',
       'Civilian population aged 15 years and over ;  > Males ;',
       'Civilian population aged 15 years and over ;  > Females ;'],
      dtype='object')

### Labor force status and growth change

#### Observe and Analyse the dataset

In [48]:
LabourForce_CurrentOriginal.head()

NameError: name 'LabourForce_CurrentOriginal' is not defined

#### Data Reframe plan

1. Remove uneccessary rows and rename the columns\
2. Extract Month and year

#### 1. Remove uneccessary rows and rename the columns

In [ ]:
# make a copy
LabourForce_Current = LabourForce_CurrentOriginal.copy()

In [ ]:
LabourForce_Current_PreColNames = LabourForce_Current.columns
LabourForce_Current_NewColNames = LabourForce_Current.iloc[2].to_numpy()

In [ ]:
LabourForce_Current_RemoveRows = LabourForce_Current.iloc[3:,:7]
LabourForce_Current_RemoveRows.head()

In [ ]:
LabourForce_Current_RenameColumnNames = LabourForce_Current_RemoveRows.rename(columns = {LabourForce_Current_PreColNames[0]:LabourForce_Current_NewColNames[0],
                                                                                         LabourForce_Current_PreColNames[1]:LabourForce_Current_NewColNames[1],
                                                                                         LabourForce_Current_PreColNames[2]:LabourForce_Current_NewColNames[2],
                                                                                         LabourForce_Current_PreColNames[3]:LabourForce_Current_NewColNames[3],
                                                                                         LabourForce_Current_PreColNames[4]:LabourForce_Current_NewColNames[4],
                                                                                         LabourForce_Current_PreColNames[5]:LabourForce_Current_NewColNames[5],
                                                                                         LabourForce_Current_PreColNames[6]:LabourForce_Current_NewColNames[6],
                                                                                        })

In [ ]:
LabourForce_Current_RenameColumnNames = LabourForce_Current_RenameColumnNames.rename(columns = {"Month":"Date", "State and territory (STT): ASGS (2011)":"State", "Labour force status - current month":"status_current_month", "Labour force status - previous month":"status_previous_month", "Persons - current month ('000)":"value_current_month"})

In [ ]:
LabourForce_Current_RenameColumnNames.head()

#### 2. Extract Month and year

In [ ]:
LabourForce_Current_MonthYear = LabourForce_Current_RenameColumnNames.copy()

In [ ]:
LabourForce_Current_MonthYear.dtypes

In [ ]:
LabourForce_Current_MonthYear.head()

In [ ]:
LabourForce_Current_MonthYear['Date'][3]

Observed a mix of object and datetime. The plan is to convert the column to actuall datetime formate

In [ ]:
LabourForce_Current_MonthYear['Date'] = pd.to_datetime(LabourForce_Current_MonthYear['Date'])

In [ ]:
# extract month and year
LabourForce_Current_MonthYear['Year'] = LabourForce_Current_MonthYear['Date'].dt.year
LabourForce_Current_MonthYear['Month'] = LabourForce_Current_MonthYear['Date'].dt.month

In [ ]:
LabourForce_Current_MonthYear.head()

In [ ]:
#Drop Date
LabourForce_Current_DateDroped = LabourForce_Current_MonthYear.drop('Date', axis=1)

In [ ]:
LabourForce_Current = LabourForce_Current_DateDroped.copy()

### Combine datasets

In [ ]:
LabourForce_Current.columns

In [ ]:
EmployPopulationRatial.columns

In [ ]:
CPT.columns