# Project: Australian Market Expansion Strategy - 
## Workforce-Based Business Expansion Analytics

### Description:

Goal: explore and clean the datasets
Tech: Python\
Library: pandas, numpy, re, string\
Data Source: Australian Bureau of Statistics\
Datasets: EmploymentByState_NewSouthWales, EmploymentByState_NorthernTerritory\
Import Funtions Files: Functions.py

## Part1. Library and datasets

### Library:

In [1]:
# install
#!pip install pandas openpyxl

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import pandas as pd
import numpy as np
import re
import string
from Functions import extract_matadata, melt_and_update_columns, merge_metadata_and_melted_dataset

### Files:

Location:

In [4]:
fileLocation = '/Users/abbottting/Desktop/Project/AMES/OriginalData'

In [5]:
#CPIMonthly_path = fileLocation + '/' + "CPI_MonthlyPercentageChange.xlsx"
#EmployPopulationRatial_Path = fileLocation + '/' + 'EmploymentToPopulationRatio.csv'
EmploymentByState_NewSouthWales_Path = fileLocation + '/'  + 'EmploymentByState_NewSouthWales.xlsx'
EmploymentByState_NorthernTerritory_Path = fileLocation + '/'  + 'EmploymentByState_NorthernTerritory.xlsx'

Read files

In [6]:
#CPI_MonthlyOriginal = pd.read_excel(CPIMonthly_path, sheet_name = "Data1")
#EmployPopulationRatial_Original = pd.read_csv(EmployPopulationRatial_Path)
EmploymentByState_NewSouthWales_Original = pd.read_excel(EmploymentByState_NewSouthWales_Path, sheet_name = 'Data1')
EmploymentByState_NorthernTerritory_Original = pd.read_excel(EmploymentByState_NorthernTerritory_Path, sheet_name = 'Data1')
#The following dataset is not required 
#LabourForce_CurrentOriginal = pd.read_excel(LabourForce_Path, sheet_name = "Data 1")
#LabourForce_PreviousOriginal = pd.read_excel(LabourForce_Path, sheet_name = "Data 2")

## Part2. Data Extraction and transformation

### EmploymentByState_NewSouthWales

#### Observe and Analyse the dataset

In [7]:
EmploymentByState_NewSouthWales_Original.head(10)

,Unnamed: 0,Employed total ; Persons ;,Employed total ; Persons ;.1,Employed total ; Persons ;.2,Employed total ; > Males ;,Employed total ; > Males ;.1,Employed total ; > Males ;.2,Employed total ; > Females ;,Employed total ; > Females ;.1,Employed total ; > Females ;.2,...,Participation rate ; > Males ;.2,Participation rate ; > Females ;,Participation rate ; > Females ;.1,Participation rate ; > Females ;.2,Not in the labour force (NILF) ; Persons ;,Not in the labour force (NILF) ; > Males ;,Not in the labour force (NILF) ; > Females ;,Civilian population aged 15 years and over ; Persons ;,Civilian population aged 15 years and over ; > Males ;,Civilian population aged 15 years and over ; > Females ;
0,Unit,000,000,000,000,000,000,000,000,000,...,Percent,Percent,Percent,Percent,000,000,000,000,000,000
1,Series Type,Trend,Seasonally Adjusted,Original,Trend,Seasonally Adjusted,Original,Trend,Seasonally Adjusted,Original,...,Original,Trend,Seasonally Adjusted,Original,Original,Original,Original,Original,Original,Original
2,Data Type,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,...,PERCENT,PERCENT,PERCENT,PERCENT,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK
3,Frequency,Month,Month,Month,Month,Month,Month,Month,Month,Month,...,Month,Month,Month,Month,Month,Month,Month,Month,Month,Month
4,Collection Month,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
5,Series Start,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,...,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00
6,Series End,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,...,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00
7,No. Obs,576,576,576,576,576,576,576,576,576,...,576,576,576,576,576,576,576,576,576,576
8,Series ID,A84423937R,A84423265K,A84423601K,A84423825W,A84423153T,A84423489W,A84424049K,A84423377C,A84423713C,...,A84423495T,A84424055F,A84423383X,A84423719T,A84423604T,A84423492K,A84423716K,A84423605V,A84423493L,A84423717L
9,1978-02-01 00:00:00,2108.211696,2113.937155,2114.116622,1363.006258,1365.43433,1369.400359,745.205437,748.502825,744.716262,...,79.757877,42.768707,43.022597,43.388591,1447.67271,371.382833,1076.289877,3735.891949,1834.702955,1901.188995

In [8]:
EmploymentByState_NewSouthWales_Original.columns

Index(['Unnamed: 0', 'Employed total ;  Persons ;',
       'Employed total ;  Persons ;.1', 'Employed total ;  Persons ;.2',
       'Employed total ;  > Males ;', 'Employed total ;  > Males ;.1',
       'Employed total ;  > Males ;.2', 'Employed total ;  > Females ;',
       'Employed total ;  > Females ;.1', 'Employed total ;  > Females ;.2',
       '> Employed full-time ;  Persons ;',
       '> Employed full-time ;  Persons ;.1',
       '> Employed full-time ;  Persons ;.2',
       '> Employed full-time ;  > Males ;',
       '> Employed full-time ;  > Males ;.1',
       '> Employed full-time ;  > Males ;.2',
       '> Employed full-time ;  > Females ;',
       '> Employed full-time ;  > Females ;.1',
       '> Employed full-time ;  > Females ;.2',
       '> Employed part-time ;  Persons ;',
       '> Employed part-time ;  > Males ;',
       '> Employed part-time ;  > Females ;',
       'Employment to population ratio ;  Persons ;',
       'Employment to population ratio ;  Persons ;.1',
       'Employment to population ratio ;  Persons ;.2',
       'Employment to population ratio ;  > Males ;',
       'Employment to population ratio ;  > Males ;.1',
       'Employment to population ratio ;  > Males ;.2',
       'Employment to population ratio ;  > Females ;',
       'Employment to population ratio ;  > Females ;.1',
       'Employment to population ratio ;  > Females ;.2',
       'Unemployed total ;  Persons ;', 'Unemployed total ;  Persons ;.1',
       'Unemployed total ;  Persons ;.2', 'Unemployed total ;  > Males ;',
       'Unemployed total ;  > Males ;.1', 'Unemployed total ;  > Males ;.2',
       'Unemployed total ;  > Females ;', 'Unemployed total ;  > Females ;.1',
       'Unemployed total ;  > Females ;.2',
       '> Unemployed looked for full-time work ;  Persons ;',
       '> Unemployed looked for full-time work ;  > Males ;',
       '> Unemployed looked for full-time work ;  > Females ;',
       '> Unemployed looked for only part-time work ;  Persons ;',
       '> Unemployed looked for only part-time work ;  > Males ;',
       '> Unemployed looked for only part-time work ;  > Females ;',
       'Unemployment rate ;  Persons ;', 'Unemployment rate ;  Persons ;.1',
       'Unemployment rate ;  Persons ;.2', 'Unemployment rate ;  > Males ;',
       'Unemployment rate ;  > Males ;.1', 'Unemployment rate ;  > Males ;.2',
       'Unemployment rate ;  > Females ;',
       'Unemployment rate ;  > Females ;.1',
       'Unemployment rate ;  > Females ;.2',
       '> Unemployment rate looked for full-time work ;  Persons ;',
       '> Unemployment rate looked for full-time work ;  > Males ;',
       '> Unemployment rate looked for full-time work ;  > Females ;',
       '> Unemployment rate looked for only part-time work ;  Persons ;',
       '> Unemployment rate looked for only part-time work ;  > Males ;',
       '> Unemployment rate looked for only part-time work ;  > Females ;',
       'Labour force total ;  Persons ;', 'Labour force total ;  Persons ;.1',
       'Labour force total ;  Persons ;.2', 'Labour force total ;  > Males ;',
       'Labour force total ;  > Males ;.1',
       'Labour force total ;  > Males ;.2',
       'Labour force total ;  > Females ;',
       'Labour force total ;  > Females ;.1',
       'Labour force total ;  > Females ;.2',
       'Participation rate ;  Persons ;', 'Participation rate ;  Persons ;.1',
       'Participation rate ;  Persons ;.2', 'Participation rate ;  > Males ;',
       'Participation rate ;  > Males ;.1',
       'Participation rate ;  > Males ;.2',
       'Participation rate ;  > Females ;',
       'Participation rate ;  > Females ;.1',
       'Participation rate ;  > Females ;.2',
       'Not in the labour force (NILF) ;  Persons ;',
       'Not in the labour force (NILF) ;  > Males ;',
       'Not in the labour force (NILF) ;  > Females ;',
       'Civilian population aged 15 years and over ;  Persons ;',
       'Civilian population aged 15 years and over ;  > Males ;',
       'Civilian population aged 15 years and over ;  > Females ;'],
      dtype='str')

#### Data processing plan

Step 1. Turn the first to eighth row index into columns.\
Step 2. Turn the rest of the index into variables of a column called date.\
Step 3. Consistently transform column by column.\
Step 4. Use the code to develop automation and functions in other files for later use.

#### Step1. Turn the first to eighth row index into mata data

In [9]:
# Extract the first eight rows into metadata and transpose the matrix
mata_data = EmploymentByState_NewSouthWales_Original.iloc[:9].T
mata_data.head()

,0,1,2,3,4,5,6,7,8
Unnamed: 0,Unit,Series Type,Data Type,Frequency,Collection Month,Series Start,Series End,No. Obs,Series ID
Employed total ; Persons ;,000,Trend,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576,A84423937R
Employed total ; Persons ;.1,000,Seasonally Adjusted,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576,A84423265K
Employed total ; Persons ;.2,000,Original,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576,A84423601K
Employed total ; > Males ;,000,Trend,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576,A84423825W

In [10]:
# reset index
mata_data_reindex = mata_data.reset_index()
mata_data_reindex.head()

,index,0,1,2,3,4,5,6,7,8
0,Unnamed: 0,Unit,Series Type,Data Type,Frequency,Collection Month,Series Start,Series End,No. Obs,Series ID
1,Employed total ; Persons ;,000,Trend,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576,A84423937R
2,Employed total ; Persons ;.1,000,Seasonally Adjusted,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576,A84423265K
3,Employed total ; Persons ;.2,000,Original,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576,A84423601K
4,Employed total ; > Males ;,000,Trend,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576,A84423825W

In [11]:
# extract first row and use it as column names
new_columns = list(mata_data_reindex.iloc[0])
new_columns

['Unnamed: 0',
 'Unit',
 'Series Type',
 'Data Type',
 'Frequency',
 'Collection Month',
 'Series Start',
 'Series End',
 'No. Obs',
 'Series ID']

In [12]:
# update column format
for i in range(len(new_columns)):
    column_name = new_columns[i].lower()
    punctuation_removed = column_name.translate(str.maketrans('','',string.punctuation))
    new_columns[i] = punctuation_removed.replace(' ', '_')

In [13]:
# assign, remove first row, reset index
mata_data_reindex.columns = new_columns
mata_data_updated_columns = mata_data_reindex.iloc[1:].reset_index(drop = True)
mata_data_updated_columns.head(5)

,unnamed_0,unit,series_type,data_type,frequency,collection_month,series_start,series_end,no_obs,series_id
0,Employed total ; Persons ;,000,Trend,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576,A84423937R
1,Employed total ; Persons ;.1,000,Seasonally Adjusted,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576,A84423265K
2,Employed total ; Persons ;.2,000,Original,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576,A84423601K
3,Employed total ; > Males ;,000,Trend,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576,A84423825W
4,Employed total ; > Males ;.1,000,Seasonally Adjusted,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576,A84423153T

In [14]:
# update the first column name
first_column = mata_data_updated_columns.columns[0]
print(f'original column name: {first_column}')
mata_data_updated_columns.rename(columns={first_column : 'variable'}, inplace = True)
print(f'new column name: {mata_data_updated_columns.columns[0]}')
# assign values to a list in first column
variables_original = list(mata_data_updated_columns['variable'])

original column name: unnamed_0
new column name: variable

In [15]:
# Split the variable with genders
variables = []
genders = []
for i, o in enumerate(variables_original):
    splited_object = o.split(';')
    #get the variable and gender from the string
    one_variable = splited_object[0].strip()
    strip_chars = string.whitespace + string.punctuation + string.digits
    one_gender = splited_object[1].strip(strip_chars)
    variables.append(one_variable)
    genders.append(one_gender)

# add gender and variable to the dataset
mata_data_updated_columns.insert(1, 'gender', genders)
mata_data_updated_columns['variable'] = variables

In [16]:
mata_data_updated_columns.head()

,variable,gender,unit,series_type,data_type,frequency,collection_month,series_start,series_end,no_obs,series_id
0,Employed total,Persons,000,Trend,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576,A84423937R
1,Employed total,Persons,000,Seasonally Adjusted,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576,A84423265K
2,Employed total,Persons,000,Original,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576,A84423601K
3,Employed total,Males,000,Trend,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576,A84423825W
4,Employed total,Males,000,Seasonally Adjusted,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576,A84423153T

#### Step2. use series ID as column, prepare to melt the rest of dataset including series id, date, and values

In [21]:
# check if series_id has no duplicate
duplicate_rows = mata_data_updated_columns[mata_data_updated_columns.duplicated(subset=['series_id'], keep=False)]
duplicate_rows.shape

(0, 11)

In [22]:
value = EmploymentByState_NewSouthWales_Original.iloc[9:]

In [23]:
#check data
value.head().iloc[:, :5]

,Unnamed: 0,Employed total ; Persons ;,Employed total ; Persons ;.1,Employed total ; Persons ;.2,Employed total ; > Males ;
9,1978-02-01 00:00:00,2108.211696,2113.937155,2114.116622,1363.006258
10,1978-03-01 00:00:00,2109.021527,2094.809924,2110.179431,1361.723258
11,1978-04-01 00:00:00,2109.854462,2107.530544,2115.063279,1360.306263
12,1978-05-01 00:00:00,2111.157961,2111.430838,2111.268984,1358.992234
13,1978-06-01 00:00:00,2112.979788,2112.439636,2113.247138,1357.54763

In [24]:
# Get series ID
series_id = EmploymentByState_NewSouthWales_Original.loc[8]

In [25]:
# use series ID as new columnnames
value_series_id = value.rename(columns = series_id)
value_series_id.head().iloc[:, :5]

              Series ID   A84423937R   A84423265K   A84423601K   A84423825W
9   1978-02-01 00:00:00  2108.211696  2113.937155  2114.116622  1363.006258
10  1978-03-01 00:00:00  2109.021527  2094.809924  2110.179431  1361.723258
11  1978-04-01 00:00:00  2109.854462  2107.530544  2115.063279  1360.306263
12  1978-05-01 00:00:00  2111.157961  2111.430838  2111.268984  1358.992234
13  1978-06-01 00:00:00  2112.979788  2112.439636  2113.247138   1357.54763

In [26]:
# update the first column name to 'date'
value_date = value_series_id.rename(columns = {'Series ID': 'date'})

In [27]:
#melt the data set
value_melted = pd.melt(value_date, id_vars = 'date', var_name = 'series_id', value_name='value')
value_melted.head()

        date   series_id        value
0 1978-02-01  A84423937R  2108.211696
1 1978-03-01  A84423937R  2109.021527
2 1978-04-01  A84423937R  2109.854462
3 1978-05-01  A84423937R  2111.157961
4 1978-06-01  A84423937R  2112.979788

#### Step3. join part of metadata and values by series_id

In [17]:
mata_data_updated_columns.head()

,variable,gender,unit,series_type,data_type,frequency,collection_month,series_start,series_end,no_obs,series_id
0,Employed total,Persons,000,Trend,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576,A84423937R
1,Employed total,Persons,000,Seasonally Adjusted,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576,A84423265K
2,Employed total,Persons,000,Original,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576,A84423601K
3,Employed total,Males,000,Trend,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576,A84423825W
4,Employed total,Males,000,Seasonally Adjusted,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576,A84423153T

In [18]:
# analys the values in unit, data_type, frequency, collection_month, no_obs
unit_values = set(mata_data_updated_columns['unit'])
data_type_values = set(mata_data_updated_columns['data_type'])
frequency_values = set(mata_data_updated_columns['frequency'])
collection_month_values = set(mata_data_updated_columns['collection_month'])
no_obs_values = set(mata_data_updated_columns['no_obs'])
print(unit_values, data_type_values, frequency_values, collection_month_values, no_obs_values)

{'000', 'Percent'} {'PERCENT', 'STOCK'} {'Month'} {1} {576}

In [19]:
# select column to merge
selected_matadata = mata_data_updated_columns[['variable', 'gender', 'series_type', 'series_id']]
selected_matadata.head()

         variable   gender          series_type   series_id
0  Employed total  Persons                Trend  A84423937R
1  Employed total  Persons  Seasonally Adjusted  A84423265K
2  Employed total  Persons             Original  A84423601K
3  Employed total    Males                Trend  A84423825W
4  Employed total    Males  Seasonally Adjusted  A84423153T

In [29]:
# Merge df1 and df2 using the shared column 'series_id'
final_dataset = pd.merge(value_melted, selected_matadata, on='series_id', how='left')
final_dataset = final_dataset[['date','series_id', 'variable', 'gender', 'series_type', 'value']]
final_dataset.head()

        date   series_id        variable   gender series_type        value
0 1978-02-01  A84423937R  Employed total  Persons       Trend  2108.211696
1 1978-03-01  A84423937R  Employed total  Persons       Trend  2109.021527
2 1978-04-01  A84423937R  Employed total  Persons       Trend  2109.854462
3 1978-05-01  A84423937R  Employed total  Persons       Trend  2111.157961
4 1978-06-01  A84423937R  Employed total  Persons       Trend  2112.979788

In [30]:
final_dataset.shape

(48384, 6)

### EmploymentByState_NorthernTerritory

#### Observe and Analyse the dataset

In [12]:
EmploymentByState_NorthernTerritory_Original.head()

,Unnamed: 0,Employed total ; Persons ;,Employed total ; > Males ;,Employed total ; > Females ;,> Employed full-time ; Persons ;,> Employed full-time ; > Males ;,> Employed full-time ; > Females ;,Employment to population ratio ; Persons ;,Employment to population ratio ; > Males ;,Employment to population ratio ; > Females ;,...,Unemployed total ; > Females ;,Unemployment rate ; Persons ;,Unemployment rate ; > Males ;,Unemployment rate ; > Females ;,Labour force total ; Persons ;,Labour force total ; > Males ;,Labour force total ; > Females ;,Participation rate ; Persons ;,Participation rate ; > Males ;,Participation rate ; > Females ;
0,Unit,000,000,000,000,000,000,Percent,Percent,Percent,...,000,Percent,Percent,Percent,000,000,000,Percent,Percent,Percent
1,Series Type,Seasonally Adjusted,Seasonally Adjusted,Seasonally Adjusted,Seasonally Adjusted,Seasonally Adjusted,Seasonally Adjusted,Seasonally Adjusted,Seasonally Adjusted,Seasonally Adjusted,...,Seasonally Adjusted,Seasonally Adjusted,Seasonally Adjusted,Seasonally Adjusted,Seasonally Adjusted,Seasonally Adjusted,Seasonally Adjusted,Seasonally Adjusted,Seasonally Adjusted,Seasonally Adjusted
2,Data Type,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,PERCENT,PERCENT,PERCENT,...,STOCK,PERCENT,PERCENT,PERCENT,STOCK,STOCK,STOCK,PERCENT,PERCENT,PERCENT
3,Frequency,Month,Month,Month,Month,Month,Month,Month,Month,Month,...,Month,Month,Month,Month,Month,Month,Month,Month,Month,Month
4,Collection Month,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [13]:
EmploymentByState_NorthernTerritory_Original.shape

(585, 22)

In [14]:
EmploymentByState_NorthernTerritory_Original.iloc[:9]

,Unnamed: 0,Employed total ; Persons ;,Employed total ; > Males ;,Employed total ; > Females ;,> Employed full-time ; Persons ;,> Employed full-time ; > Males ;,> Employed full-time ; > Females ;,Employment to population ratio ; Persons ;,Employment to population ratio ; > Males ;,Employment to population ratio ; > Females ;,...,Unemployed total ; > Females ;,Unemployment rate ; Persons ;,Unemployment rate ; > Males ;,Unemployment rate ; > Females ;,Labour force total ; Persons ;,Labour force total ; > Males ;,Labour force total ; > Females ;,Participation rate ; Persons ;,Participation rate ; > Males ;,Participation rate ; > Females ;
0,Unit,000,000,000,000,000,000,Percent,Percent,Percent,...,000,Percent,Percent,Percent,000,000,000,Percent,Percent,Percent
1,Series Type,Seasonally Adjusted,Seasonally Adjusted,Seasonally Adjusted,Seasonally Adjusted,Seasonally Adjusted,Seasonally Adjusted,Seasonally Adjusted,Seasonally Adjusted,Seasonally Adjusted,...,Seasonally Adjusted,Seasonally Adjusted,Seasonally Adjusted,Seasonally Adjusted,Seasonally Adjusted,Seasonally Adjusted,Seasonally Adjusted,Seasonally Adjusted,Seasonally Adjusted,Seasonally Adjusted
2,Data Type,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,PERCENT,PERCENT,PERCENT,...,STOCK,PERCENT,PERCENT,PERCENT,STOCK,STOCK,STOCK,PERCENT,PERCENT,PERCENT
3,Frequency,Month,Month,Month,Month,Month,Month,Month,Month,Month,...,Month,Month,Month,Month,Month,Month,Month,Month,Month,Month
4,Collection Month,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
5,Series Start,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,...,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00
6,Series End,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,...,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00
7,No. Obs,576,576,576,576,576,576,576,576,576,...,576,576,576,576,576,576,576,576,576,576
8,Series ID,A84423335F,A84423223L,A84423447X,A84423343F,A84423231L,A84423455X,A84423342C,A84423230K,A84423454W,...,A84423448A,A84423340X,A84423228X,A84423452T,A84423337K,A84423225T,A84423449C,A84423341A,A84423229A,A84423453V

#### Step1. Turn the first to eighth row index into mata data

In [31]:
NorthTerritory_metadata = extract_matadata(EmploymentByState_NorthernTerritory_Original)
NorthTerritory_metadata.head()

,variable,gender,unit,series_type,data_type,frequency,collection_month,series_start,series_end,no_obs,series_id
0,Employed total,Persons,000,Seasonally Adjusted,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576,A84423335F
1,Employed total,Males,000,Seasonally Adjusted,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576,A84423223L
2,Employed total,Females,000,Seasonally Adjusted,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576,A84423447X
3,> Employed full-time,Persons,000,Seasonally Adjusted,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576,A84423343F
4,> Employed full-time,Males,000,Seasonally Adjusted,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576,A84423231L

#### Step2. use series ID as column, prepare to melt the rest of dataset including series id, date, and values

In [33]:
# check if series_id has no duplicate
duplicate_rows = NorthTerritory_metadata[NorthTerritory_metadata.duplicated(subset=['series_id'], keep=False)]
duplicate_rows.shape

(0, 11)

In [34]:
value_melted = melt_and_update_columns(EmploymentByState_NorthernTerritory_Original)
value_melted

            date   series_id      value
0     1978-02-01  A84423335F  41.624292
1     1978-03-01  A84423335F  45.341661
2     1978-04-01  A84423335F  44.021738
3     1978-05-01  A84423335F  45.769913
4     1978-06-01  A84423335F  42.605502
...          ...         ...        ...
12091 2025-09-01  A84423453V  72.001683
12092 2025-10-01  A84423453V  71.069717
12093 2025-11-01  A84423453V  71.838167
12094 2025-12-01  A84423453V  72.496493
12095 2026-01-01  A84423453V  72.019522

[12096 rows x 3 columns]

#### Step3. join part of metadata and values by series_id

In [35]:
# select the variables in the matadata
selected_columns = ['variable', 'gender', 'series_type', 'series_id']
order = ['date','series_id', 'variable', 'gender', 'series_type', 'value']

# merge
final_dataset = merge_metadata_and_melted_dataset(
    metadata = NorthTerritory_metadata,
    melted_dataset = value_melted,
    selected_columns = selected_columns
)

# reorder columns
final_dataset = final_dataset[order]

# print
final_dataset.head()

,date,series_id,variable,gender,series_type,value
0,1978-02-01,A84423335F,Employed total,Persons,Seasonally Adjusted,41.624292
1,1978-03-01,A84423335F,Employed total,Persons,Seasonally Adjusted,45.341661
2,1978-04-01,A84423335F,Employed total,Persons,Seasonally Adjusted,44.021738
3,1978-05-01,A84423335F,Employed total,Persons,Seasonally Adjusted,45.769913
4,1978-06-01,A84423335F,Employed total,Persons,Seasonally Adjusted,42.605502

### Labor force status and growth change

#### Observe and Analyse the dataset

In [ ]:
LabourForce_CurrentOriginal.head()

#### Data Reframe plan

1. Remove uneccessary rows and rename the columns\
2. Extract Month and year

#### 1. Remove uneccessary rows and rename the columns

In [ ]:
# make a copy
LabourForce_Current = LabourForce_CurrentOriginal.copy()

In [ ]:
LabourForce_Current_PreColNames = LabourForce_Current.columns
LabourForce_Current_NewColNames = LabourForce_Current.iloc[2].to_numpy()

In [ ]:
LabourForce_Current_RemoveRows = LabourForce_Current.iloc[3:,:7]
LabourForce_Current_RemoveRows.head()

In [ ]:
LabourForce_Current_RenameColumnNames = LabourForce_Current_RemoveRows.rename(columns = {LabourForce_Current_PreColNames[0]:LabourForce_Current_NewColNames[0],
                                                                                         LabourForce_Current_PreColNames[1]:LabourForce_Current_NewColNames[1],
                                                                                         LabourForce_Current_PreColNames[2]:LabourForce_Current_NewColNames[2],
                                                                                         LabourForce_Current_PreColNames[3]:LabourForce_Current_NewColNames[3],
                                                                                         LabourForce_Current_PreColNames[4]:LabourForce_Current_NewColNames[4],
                                                                                         LabourForce_Current_PreColNames[5]:LabourForce_Current_NewColNames[5],
                                                                                         LabourForce_Current_PreColNames[6]:LabourForce_Current_NewColNames[6],
                                                                                        })

In [ ]:
LabourForce_Current_RenameColumnNames = LabourForce_Current_RenameColumnNames.rename(columns = {"Month":"Date", "State and territory (STT): ASGS (2011)":"State", "Labour force status - current month":"status_current_month", "Labour force status - previous month":"status_previous_month", "Persons - current month ('000)":"value_current_month"})

In [ ]:
LabourForce_Current_RenameColumnNames.head()

#### 2. Extract Month and year

In [ ]:
LabourForce_Current_MonthYear = LabourForce_Current_RenameColumnNames.copy()

In [ ]:
LabourForce_Current_MonthYear.dtypes

In [ ]:
LabourForce_Current_MonthYear.head()

In [ ]:
LabourForce_Current_MonthYear['Date'][3]

Observed a mix of object and datetime. The plan is to convert the column to actuall datetime formate

In [ ]:
LabourForce_Current_MonthYear['Date'] = pd.to_datetime(LabourForce_Current_MonthYear['Date'])

In [ ]:
# extract month and year
LabourForce_Current_MonthYear['Year'] = LabourForce_Current_MonthYear['Date'].dt.year
LabourForce_Current_MonthYear['Month'] = LabourForce_Current_MonthYear['Date'].dt.month

In [ ]:
LabourForce_Current_MonthYear.head()

In [ ]:
#Drop Date
LabourForce_Current_DateDroped = LabourForce_Current_MonthYear.drop('Date', axis=1)

In [ ]:
LabourForce_Current = LabourForce_Current_DateDroped.copy()

### Combine datasets

In [ ]:
LabourForce_Current.columns

In [ ]:
EmployPopulationRatial.columns

## Archive Codes

### Employment to population Ration

#### Observe and Analyse the dataset

In [ ]:
EmployPopulationRatial_Original

In [ ]:
EmployPopulationRatial = EmployPopulationRatial_Original.copy()

Observation:\
The size of the data set is 124X1. The only column is named Employment-to-population ratio. Under the column there are three sub-columns. The first column is datetime, and the rest are the numerical data. The last two rows are not the value of the datasets.

#### Data processing plan

Step1 - reset index and the column names.\
Step2 - remove the last two rows.\
Step3 - extract month and year.\
Step4 - convert the datatypes of month and year to numeric.\
Step5 - convert data in seasonally adjusted from percentage to decimal

#### Step1 - reset index and the column names.

In [ ]:
EmployPopulationRatial_ResetIndex = EmployPopulationRatial.reset_index()

In [ ]:
EmployPopulationRatial_ResetColumnName = EmployPopulationRatial_ResetIndex.copy()
EmployPopulationRatial_ResetColumnName.columns = EmployPopulationRatial_ResetColumnName.iloc[0].tolist()
EmployPopulationRatial_ResetColumnName = EmployPopulationRatial_ResetColumnName.iloc[1:]

In [ ]:
OriginalColumnNames = EmployPopulationRatial_ResetColumnName.columns
EmployPopulationRatial_ResetColumnName = EmployPopulationRatial_ResetColumnName.rename(columns = {OriginalColumnNames[0]:'Date', OriginalColumnNames[1]:'Employment_Population_Ratio', OriginalColumnNames[2]:'Ratio_SeasonallyAdjusted'})

In [ ]:
EmployPopulationRatial_ResetColumnName.head()

#### Step2 - remove the last two rows.

In [ ]:
EmployPopulationRatial_RemovedRows = EmployPopulationRatial_ResetColumnName.iloc[:121] 
EmployPopulationRatial_RemovedRows

#### Step3 - extract month and year.

In [ ]:
EmployPopulationRatial_ExtractMonthYear = EmployPopulationRatial_RemovedRows.copy()

In [ ]:
MonthYear = EmployPopulationRatial_ExtractMonthYear['Date'].str.split('-', expand=True)

In [ ]:
MonthYear.columns

In [ ]:
EmployPopulationRatial_ExtractMonthYear['Month_Name'] = MonthYear[0]
EmployPopulationRatial_ExtractMonthYear['Year'] = '20' + MonthYear[1]

In [ ]:
EmployPopulationRatial_ExtractMonthYear['Month'] = pd.to_datetime(EmployPopulationRatial_ExtractMonthYear['Month_Name'], format='%b').dt.month

In [ ]:
# drop Date, Month_Name
EmployPopulationRatial = EmployPopulationRatial_ExtractMonthYear.drop(columns = ['Date', 'Month_Name'])

In [ ]:
EmployPopulationRatial.head()

#### Step4 - convert the datatypes of month and year to numeric.

In [ ]:
EmployPopulationRatial['Year'] = EmployPopulationRatial['Year'].astype(int)

In [ ]:
EmployPopulationRatial['Month'] = EmployPopulationRatial['Month'].astype(int)

#### Step5 - convert data in seasonally adjusted from percentage to decimal

In [ ]:
#convert string to float then transfrom the data
EmployPopulationRatial['Ratio_SeasonallyAdjusted'] = EmployPopulationRatial['Ratio_SeasonallyAdjusted'].astype(float)/100

In [ ]:
#drop first column
EmployPopulationRatial_cleaned = EmployPopulationRatial[['Ratio_SeasonallyAdjusted', 'Year', 'Month']]

In [ ]:
EmployPopulationRatial_cleaned.head(5)

### CPI_MonthlyPath(Archive)

#### Observe and Analyse the dataset

In [ ]:
CPI_MonthlyPath = CPI_MonthlyOriginal.copy()
CPI_MonthlyPath.head()

Observation:\
Data set type - structural data, wide data sets
Size - 30rows X 133 columns
columns- first column contains the information of each rows without a column name which suppose to be the column names, including but not limited to Unit, series type, data type, etc. From the seconde column to the last column, the column name contains the industry, including all groups, non-alcoholic beverages, bread and cereal product, etc. 
Data types - the data sets contain categorical, numerical and datetime datasets

#### Data processing plan

Step1 - transfer the wide data to long.\
Step2 - extract the industries info and name the column industry.\
Step3 - extract the Month and Year information from the datetime (located in the first row originally), named as Month and Year.\
Step4 - deleted the columns/information that is not neceessary, for example colleciton month, series start, etc.\

#### Step1 - transfer the wide data to long.

In [ ]:
CPT_Wide = CPI_MonthlyPath.T

#### Step2 - extract the industries info and name the column industry.

In [ ]:
CPT_Wide.head()

In [ ]:
CPT_Wide_resetIndex = CPT_Wide.reset_index()

In [ ]:
CPT_Wide_resetIndex.head()

In [ ]:
#make first row as column name
CPT_Wide_resetIndex.columns = CPT_Wide_resetIndex.iloc[0]
CPT_DropFirstRow = CPT_Wide_resetIndex.drop(0, axis = 0)

In [ ]:
#name the first column industry
firstColumnName = CPT_DropFirstRow.columns[0]
rename = 'Industry'
CPT_rename = CPT_DropFirstRow.rename(columns = {firstColumnName:rename})

In [ ]:
#reset index
CPT_Wide_resetIndex = CPT_rename.reset_index(drop=True)

In [ ]:
#extract the industry
CPT_Wide_resetIndex['Industry'] = CPT_Wide_resetIndex['Industry'].str.split(' ; ', expand=True)[1]

#### Step3 - extract the Month and Year information from the datetime (located in the first row originally), named as Month and Year.

In [ ]:
CPT_Wide_resetIndex.columns[10:]

In [ ]:
#Get the columns that are not CPT with dates
CPT_nonDateColumnNames = CPT_Wide_resetIndex.columns[:10].tolist()
CPT_nonDateColumnNames

In [ ]:
#Melt the dataframe
CPT_MeltedDateTime = pd.melt(CPT_Wide_resetIndex, id_vars=CPT_nonDateColumnNames, var_name = 'DateTime', value_name = 'CPT_Changes')

In [ ]:
CPT_MeltedDateTime.head()

In [ ]:
CPT_MeltedDateTime.dtypes

In [ ]:
CPT_MeltedDateTime['Year'] = CPT_MeltedDateTime['DateTime'].dt.year

In [ ]:
CPT_MeltedDateTime['Month'] = CPT_MeltedDateTime['DateTime'].dt.month

In [ ]:
CPT_MeltedDateTime.head()

In [ ]:
CPT_MeltedDateTime.dtypes

#### Step4 - deleted the columns/information that is not neceessary, for example colleciton month, series start, etc.

In [ ]:
CPT = CPT_MeltedDateTime.copy()

In [ ]:
CPT['No. Obs'].unique()

Remove Unit, Series Type, Data Type, Frequency, Collection Month, No.Obs, because there is only one value in these columns

In [ ]:
dropedColumns = ['Unit', 'Series Type', 'Data Type', 'Frequency', 'Collection Month', 'No. Obs']

In [ ]:
CPT_DropedColumns = CPT.drop(columns = dropedColumns, axis = 1)

Also dropped Series Start, Series end and Series ID cause its not relavant to CPT changes. Dropped DateTime Cause we already have Year and Month

In [ ]:
dropedColumns = ['Series Start', 'Series End', 'DateTime', 'Series ID']

In [ ]:
CPT_DropedDates = CPT_DropedColumns.drop(columns = dropedColumns, axis = 1)

In [ ]:
CPT_DropedDates.shape

In [ ]:
CPT = CPT_DropedDates.copy()