# Project: Australian Market Expansion Strategy - 
## Workforce-Based Business Expansion Analytics
### Description:

Goal: explore and clean the data 
Tech: Python\
Library: panda 
Data Source: Australian Bureau of Statistics

Data:\
All groups CPI, index numbers and percentage changes.xlsx

### Library:

In [19]:
# install
#!pip install pandas openpyxl

In [148]:
import pandas as pd
import numpy as np
import re
import string

### Files:

Location:

In [21]:
fileLocation = 'D:\Working Station\Career & Project\Data\Australian_Market_Expansion_Strategy\OriginalData'

In [22]:
#CPIMonthly_path = fileLocation + "\\" + "CPI_MonthlyPercentageChange.xlsx"
EmployPopulationRatial_Path = fileLocation + '\\' + 'EmploymentToPopulationRatio.csv'
EmploymentByState_NewSouthWales_Path = fileLocation + '\\'  + 'EmploymentByState_NewSouthWales.xlsx'
EmploymentByState_NorthernTerrritory_Path = fileLocation + '\\'  + 'EmploymentByState_NorthernTerrritory.xlsx'

Read files

In [23]:
#CPI_MonthlyOriginal = pd.read_excel(CPIMonthly_path, sheet_name = "Data1")
#EmployPopulationRatial_Original = pd.read_csv(EmployPopulationRatial_Path)
EmploymentByState_NewSouthWales_Original = pd.read_excel(EmploymentByState_NewSouthWales_Path, sheet_name = 'Data1')
#EmploymentByState_NorthernTerrritory_Original = pd.read_excel(EmploymentByState_NorthernTerrritory_Path, sheet_name = 'Data1')
#The following dataset is not required 
#LabourForce_CurrentOriginal = pd.read_excel(LabourForce_Path, sheet_name = "Data 1")
#LabourForce_PreviousOriginal = pd.read_excel(LabourForce_Path, sheet_name = "Data 2")

### EmploymentByState_NewSouthWales

#### Observe and Analyse the dataset

In [24]:
EmploymentByState_NewSouthWales_Original.head(10)

,Unnamed: 0,Employed total ; Persons ;,Employed total ; Persons ;.1,Employed total ; Persons ;.2,Employed total ; > Males ;,Employed total ; > Males ;.1,Employed total ; > Males ;.2,Employed total ; > Females ;,Employed total ; > Females ;.1,Employed total ; > Females ;.2,...,Participation rate ; > Males ;.2,Participation rate ; > Females ;,Participation rate ; > Females ;.1,Participation rate ; > Females ;.2,Not in the labour force (NILF) ; Persons ;,Not in the labour force (NILF) ; > Males ;,Not in the labour force (NILF) ; > Females ;,Civilian population aged 15 years and over ; Persons ;,Civilian population aged 15 years and over ; > Males ;,Civilian population aged 15 years and over ; > Females ;
0,Unit,000,000,000,000,000,000,000,000,000,...,Percent,Percent,Percent,Percent,000,000,000,000,000,000
1,Series Type,Trend,Seasonally Adjusted,Original,Trend,Seasonally Adjusted,Original,Trend,Seasonally Adjusted,Original,...,Original,Trend,Seasonally Adjusted,Original,Original,Original,Original,Original,Original,Original
2,Data Type,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,...,PERCENT,PERCENT,PERCENT,PERCENT,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK
3,Frequency,Month,Month,Month,Month,Month,Month,Month,Month,Month,...,Month,Month,Month,Month,Month,Month,Month,Month,Month,Month
4,Collection Month,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
5,Series Start,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,...,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00,1978-02-01 00:00:00
6,Series End,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,...,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00,2026-01-01 00:00:00
7,No. Obs,576,576,576,576,576,576,576,576,576,...,576,576,576,576,576,576,576,576,576,576
8,Series ID,A84423937R,A84423265K,A84423601K,A84423825W,A84423153T,A84423489W,A84424049K,A84423377C,A84423713C,...,A84423495T,A84424055F,A84423383X,A84423719T,A84423604T,A84423492K,A84423716K,A84423605V,A84423493L,A84423717L
9,1978-02-01 00:00:00,2108.211696,2113.937155,2114.116622,1363.006258,1365.43433,1369.400359,745.205437,748.502825,744.716262,...,79.757877,42.768707,43.022597,43.388591,1447.67271,371.382833,1076.289877,3735.891949,1834.702955,1901.188995

In [25]:
EmploymentByState_NewSouthWales_Original.columns

Index(['Unnamed: 0', 'Employed total ;  Persons ;',
       'Employed total ;  Persons ;.1', 'Employed total ;  Persons ;.2',
       'Employed total ;  > Males ;', 'Employed total ;  > Males ;.1',
       'Employed total ;  > Males ;.2', 'Employed total ;  > Females ;',
       'Employed total ;  > Females ;.1', 'Employed total ;  > Females ;.2',
       '> Employed full-time ;  Persons ;',
       '> Employed full-time ;  Persons ;.1',
       '> Employed full-time ;  Persons ;.2',
       '> Employed full-time ;  > Males ;',
       '> Employed full-time ;  > Males ;.1',
       '> Employed full-time ;  > Males ;.2',
       '> Employed full-time ;  > Females ;',
       '> Employed full-time ;  > Females ;.1',
       '> Employed full-time ;  > Females ;.2',
       '> Employed part-time ;  Persons ;',
       '> Employed part-time ;  > Males ;',
       '> Employed part-time ;  > Females ;',
       'Employment to population ratio ;  Persons ;',
       'Employment to population ratio ;  Persons ;.1',
       'Employment to population ratio ;  Persons ;.2',
       'Employment to population ratio ;  > Males ;',
       'Employment to population ratio ;  > Males ;.1',
       'Employment to population ratio ;  > Males ;.2',
       'Employment to population ratio ;  > Females ;',
       'Employment to population ratio ;  > Females ;.1',
       'Employment to population ratio ;  > Females ;.2',
       'Unemployed total ;  Persons ;', 'Unemployed total ;  Persons ;.1',
       'Unemployed total ;  Persons ;.2', 'Unemployed total ;  > Males ;',
       'Unemployed total ;  > Males ;.1', 'Unemployed total ;  > Males ;.2',
       'Unemployed total ;  > Females ;', 'Unemployed total ;  > Females ;.1',
       'Unemployed total ;  > Females ;.2',
       '> Unemployed looked for full-time work ;  Persons ;',
       '> Unemployed looked for full-time work ;  > Males ;',
       '> Unemployed looked for full-time work ;  > Females ;',
       '> Unemployed looked for only part-time work ;  Persons ;',
       '> Unemployed looked for only part-time work ;  > Males ;',
       '> Unemployed looked for only part-time work ;  > Females ;',
       'Unemployment rate ;  Persons ;', 'Unemployment rate ;  Persons ;.1',
       'Unemployment rate ;  Persons ;.2', 'Unemployment rate ;  > Males ;',
       'Unemployment rate ;  > Males ;.1', 'Unemployment rate ;  > Males ;.2',
       'Unemployment rate ;  > Females ;',
       'Unemployment rate ;  > Females ;.1',
       'Unemployment rate ;  > Females ;.2',
       '> Unemployment rate looked for full-time work ;  Persons ;',
       '> Unemployment rate looked for full-time work ;  > Males ;',
       '> Unemployment rate looked for full-time work ;  > Females ;',
       '> Unemployment rate looked for only part-time work ;  Persons ;',
       '> Unemployment rate looked for only part-time work ;  > Males ;',
       '> Unemployment rate looked for only part-time work ;  > Females ;',
       'Labour force total ;  Persons ;', 'Labour force total ;  Persons ;.1',
       'Labour force total ;  Persons ;.2', 'Labour force total ;  > Males ;',
       'Labour force total ;  > Males ;.1',
       'Labour force total ;  > Males ;.2',
       'Labour force total ;  > Females ;',
       'Labour force total ;  > Females ;.1',
       'Labour force total ;  > Females ;.2',
       'Participation rate ;  Persons ;', 'Participation rate ;  Persons ;.1',
       'Participation rate ;  Persons ;.2', 'Participation rate ;  > Males ;',
       'Participation rate ;  > Males ;.1',
       'Participation rate ;  > Males ;.2',
       'Participation rate ;  > Females ;',
       'Participation rate ;  > Females ;.1',
       'Participation rate ;  > Females ;.2',
       'Not in the labour force (NILF) ;  Persons ;',
       'Not in the labour force (NILF) ;  > Males ;',
       'Not in the labour force (NILF) ;  > Females ;',
       'Civilian population aged 15 years and over ;  Persons ;',
       'Civilian population aged 15 years and over ;  > Males ;',
       'Civilian population aged 15 years and over ;  > Females ;'],
      dtype='str')

#### Data processing plan

Step 1. Turn the first to eighth row index into columns.\
Step 2. Turn the rest of the index into variables of a column called date.\
Step 3. Consistently transform column by column.\
Step 4. Use the code to develop automation and functions in other files for later use.

#### Step 1. Turn the first to eighth row index into columns

In [94]:
# Extract the first eight rows into metadata and transpose the matrix
mata_data = EmploymentByState_NewSouthWales_Original.iloc[:8].T
mata_data.head()

,0,1,2,3,4,5,6,7
Unnamed: 0,Unit,Series Type,Data Type,Frequency,Collection Month,Series Start,Series End,No. Obs
Employed total ; Persons ;,000,Trend,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576
Employed total ; Persons ;.1,000,Seasonally Adjusted,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576
Employed total ; Persons ;.2,000,Original,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576
Employed total ; > Males ;,000,Trend,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576

In [174]:
# reset index
mata_data_reindex = mata_data.reset_index()
mata_data_reindex.head()

,index,0,1,2,3,4,5,6,7
0,Unnamed: 0,Unit,Series Type,Data Type,Frequency,Collection Month,Series Start,Series End,No. Obs
1,Employed total ; Persons ;,000,Trend,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576
2,Employed total ; Persons ;.1,000,Seasonally Adjusted,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576
3,Employed total ; Persons ;.2,000,Original,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576
4,Employed total ; > Males ;,000,Trend,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576

In [204]:
# extract first row and use it as column names
new_columns = list(mata_data_reindex.iloc[0])
new_columns

['Unnamed: 0',
 'Unit',
 'Series Type',
 'Data Type',
 'Frequency',
 'Collection Month',
 'Series Start',
 'Series End',
 'No. Obs']

In [205]:
# update column format
for i in range(len(new_columns)):
    column_name = new_columns[i].lower()
    punctuation_removed = column_name.translate(str.maketrans('','',string.punctuation))
    new_columns[i] = punctuation_removed.replace(' ', '_')

In [263]:
# assign, remove first row, reset index
mata_data_reindex.columns = new_columns
mata_data_updated_columns = mata_data_reindex.iloc[1:].reset_index(drop = True)
mata_data_updated_columns

,unnamed_0,unit,series_type,data_type,frequency,collection_month,series_start,series_end,no_obs
0,Employed total ; Persons ;,000,Trend,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576
1,Employed total ; Persons ;.1,000,Seasonally Adjusted,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576
2,Employed total ; Persons ;.2,000,Original,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576
3,Employed total ; > Males ;,000,Trend,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576
4,Employed total ; > Males ;.1,000,Seasonally Adjusted,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576
...,...,...,...,...,...,...,...,...,...
79,Not in the labour force (NILF) ; > Males ;,000,Original,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576
80,Not in the labour force (NILF) ; > Females ;,000,Original,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576
81,Civilian population aged 15 years and over ; ...,000,Original,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576
82,Civilian population aged 15 years and over ; ...,000,Original,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576
83,Civilian population aged 15 years and over ; ...,000,Original,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576

In [264]:
# update the first column name
first_column = mata_data_updated_columns.columns[0]
print(first_column)
mata_data_updated_columns.rename(columns={first_column : 'variable'}, inplace = True)
mata_data_updated_columns.columns[0]

unnamed_0

'variable'

In [265]:
variables_original = list(mata_data_updated_columns['variable'])
variables_original

['Employed total ;  Persons ;',
 'Employed total ;  Persons ;.1',
 'Employed total ;  Persons ;.2',
 'Employed total ;  > Males ;',
 'Employed total ;  > Males ;.1',
 'Employed total ;  > Males ;.2',
 'Employed total ;  > Females ;',
 'Employed total ;  > Females ;.1',
 'Employed total ;  > Females ;.2',
 '> Employed full-time ;  Persons ;',
 '> Employed full-time ;  Persons ;.1',
 '> Employed full-time ;  Persons ;.2',
 '> Employed full-time ;  > Males ;',
 '> Employed full-time ;  > Males ;.1',
 '> Employed full-time ;  > Males ;.2',
 '> Employed full-time ;  > Females ;',
 '> Employed full-time ;  > Females ;.1',
 '> Employed full-time ;  > Females ;.2',
 '> Employed part-time ;  Persons ;',
 '> Employed part-time ;  > Males ;',
 '> Employed part-time ;  > Females ;',
 'Employment to population ratio ;  Persons ;',
 'Employment to population ratio ;  Persons ;.1',
 'Employment to population ratio ;  Persons ;.2',
 'Employment to population ratio ;  > Males ;',
 'Employment to population ratio ;  > Males ;.1',
 'Employment to population ratio ;  > Males ;.2',
 'Employment to population ratio ;  > Females ;',
 'Employment to population ratio ;  > Females ;.1',
 'Employment to population ratio ;  > Females ;.2',
 'Unemployed total ;  Persons ;',
 'Unemployed total ;  Persons ;.1',
 'Unemployed total ;  Persons ;.2',
 'Unemployed total ;  > Males ;',
 'Unemployed total ;  > Males ;.1',
 'Unemployed total ;  > Males ;.2',
 'Unemployed total ;  > Females ;',
 'Unemployed total ;  > Females ;.1',
 'Unemployed total ;  > Females ;.2',
 '> Unemployed looked for full-time work ;  Persons ;',
 '> Unemployed looked for full-time work ;  > Males ;',
 '> Unemployed looked for full-time work ;  > Females ;',
 '> Unemployed looked for only part-time work ;  Persons ;',
 '> Unemployed looked for only part-time work ;  > Males ;',
 '> Unemployed looked for only part-time work ;  > Females ;',
 'Unemployment rate ;  Persons ;',
 'Unemployment rate ;  Persons ;.1',
 'Unemployment rate ;  Persons ;.2',
 'Unemployment rate ;  > Males ;',
 'Unemployment rate ;  > Males ;.1',
 'Unemployment rate ;  > Males ;.2',
 'Unemployment rate ;  > Females ;',
 'Unemployment rate ;  > Females ;.1',
 'Unemployment rate ;  > Females ;.2',
 '> Unemployment rate looked for full-time work ;  Persons ;',
 '> Unemployment rate looked for full-time work ;  > Males ;',
 '> Unemployment rate looked for full-time work ;  > Females ;',
 '> Unemployment rate looked for only part-time work ;  Persons ;',
 '> Unemployment rate looked for only part-time work ;  > Males ;',
 '> Unemployment rate looked for only part-time work ;  > Females ;',
 'Labour force total ;  Persons ;',
 'Labour force total ;  Persons ;.1',
 'Labour force total ;  Persons ;.2',
 'Labour force total ;  > Males ;',
 'Labour force total ;  > Males ;.1',
 'Labour force total ;  > Males ;.2',
 'Labour force total ;  > Females ;',
 'Labour force total ;  > Females ;.1',
 'Labour force total ;  > Females ;.2',
 'Participation rate ;  Persons ;',
 'Participation rate ;  Persons ;.1',
 'Participation rate ;  Persons ;.2',
 'Participation rate ;  > Males ;',
 'Participation rate ;  > Males ;.1',
 'Participation rate ;  > Males ;.2',
 'Participation rate ;  > Females ;',
 'Participation rate ;  > Females ;.1',
 'Participation rate ;  > Females ;.2',
 'Not in the labour force (NILF) ;  Persons ;',
 'Not in the labour force (NILF) ;  > Males ;',
 'Not in the labour force (NILF) ;  > Females ;',
 'Civilian population aged 15 years and over ;  Persons ;',
 'Civilian population aged 15 years and over ;  > Males ;',
 'Civilian population aged 15 years and over ;  > Females ;']

In [266]:
# Split the variable with genders
variables = []
genders = []
for i, o in enumerate(variables_original):
    splited_object = o.split(';')
    #get the variable and gender from the string
    one_variable = splited_object[0].strip()
    strip_chars = string.whitespace + string.punctuation + string.digits
    one_gender = splited_object[1].strip(strip_chars)
    variables.append(one_variable)
    genders.append(one_gender)

In [269]:
# add gender and variable to the dataset
mata_data_updated_columns.insert(1, 'gender', genders)
mata_data_updated_columns['variable'] = variables
mata_data_updated_columns

,variable,gender,unit,series_type,data_type,frequency,collection_month,series_start,series_end,no_obs
0,Employed total,Persons,000,Trend,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576
1,Employed total,Persons,000,Seasonally Adjusted,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576
2,Employed total,Persons,000,Original,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576
3,Employed total,Males,000,Trend,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576
4,Employed total,Males,000,Seasonally Adjusted,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576
...,...,...,...,...,...,...,...,...,...,...
79,Not in the labour force (NILF),Males,000,Original,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576
80,Not in the labour force (NILF),Females,000,Original,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576
81,Civilian population aged 15 years and over,Persons,000,Original,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576
82,Civilian population aged 15 years and over,Males,000,Original,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576
83,Civilian population aged 15 years and over,Females,000,Original,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576

In [270]:
mata_data_updated_columns.head()

,variable,gender,unit,series_type,data_type,frequency,collection_month,series_start,series_end,no_obs
0,Employed total,Persons,000,Trend,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576
1,Employed total,Persons,000,Seasonally Adjusted,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576
2,Employed total,Persons,000,Original,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576
3,Employed total,Males,000,Trend,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576
4,Employed total,Males,000,Seasonally Adjusted,STOCK,Month,1,1978-02-01 00:00:00,2026-01-01 00:00:00,576

### EmploymentByState_NorthernTerrritory

In [18]:
EmploymentByState_NorthernTerrritory_Original.head()

NameError: name 'EmploymentByState_NorthernTerrritory_Original' is not defined

In [ ]:
EmploymentByState_NorthernTerrritory_Original.columns

In [ ]:
nsw_col = EmploymentByState_NewSouthWales_Original.columns
nt_col = EmploymentByState_NorthernTerrritory_Original.columns
diff_col = list(set(nt_col) ^ set(nsw_col))
diff_col
#print(len(nsw_col), len(nt_col), len(diff_col))

### Labor force status and growth change

#### Observe and Analyse the dataset

In [ ]:
LabourForce_CurrentOriginal.head()

#### Data Reframe plan

1. Remove uneccessary rows and rename the columns\
2. Extract Month and year

#### 1. Remove uneccessary rows and rename the columns

In [ ]:
# make a copy
LabourForce_Current = LabourForce_CurrentOriginal.copy()

In [ ]:
LabourForce_Current_PreColNames = LabourForce_Current.columns
LabourForce_Current_NewColNames = LabourForce_Current.iloc[2].to_numpy()

In [ ]:
LabourForce_Current_RemoveRows = LabourForce_Current.iloc[3:,:7]
LabourForce_Current_RemoveRows.head()

In [ ]:
LabourForce_Current_RenameColumnNames = LabourForce_Current_RemoveRows.rename(columns = {LabourForce_Current_PreColNames[0]:LabourForce_Current_NewColNames[0],
                                                                                         LabourForce_Current_PreColNames[1]:LabourForce_Current_NewColNames[1],
                                                                                         LabourForce_Current_PreColNames[2]:LabourForce_Current_NewColNames[2],
                                                                                         LabourForce_Current_PreColNames[3]:LabourForce_Current_NewColNames[3],
                                                                                         LabourForce_Current_PreColNames[4]:LabourForce_Current_NewColNames[4],
                                                                                         LabourForce_Current_PreColNames[5]:LabourForce_Current_NewColNames[5],
                                                                                         LabourForce_Current_PreColNames[6]:LabourForce_Current_NewColNames[6],
                                                                                        })

In [ ]:
LabourForce_Current_RenameColumnNames = LabourForce_Current_RenameColumnNames.rename(columns = {"Month":"Date", "State and territory (STT): ASGS (2011)":"State", "Labour force status - current month":"status_current_month", "Labour force status - previous month":"status_previous_month", "Persons - current month ('000)":"value_current_month"})

In [ ]:
LabourForce_Current_RenameColumnNames.head()

#### 2. Extract Month and year

In [ ]:
LabourForce_Current_MonthYear = LabourForce_Current_RenameColumnNames.copy()

In [ ]:
LabourForce_Current_MonthYear.dtypes

In [ ]:
LabourForce_Current_MonthYear.head()

In [ ]:
LabourForce_Current_MonthYear['Date'][3]

Observed a mix of object and datetime. The plan is to convert the column to actuall datetime formate

In [ ]:
LabourForce_Current_MonthYear['Date'] = pd.to_datetime(LabourForce_Current_MonthYear['Date'])

In [ ]:
# extract month and year
LabourForce_Current_MonthYear['Year'] = LabourForce_Current_MonthYear['Date'].dt.year
LabourForce_Current_MonthYear['Month'] = LabourForce_Current_MonthYear['Date'].dt.month

In [ ]:
LabourForce_Current_MonthYear.head()

In [ ]:
#Drop Date
LabourForce_Current_DateDroped = LabourForce_Current_MonthYear.drop('Date', axis=1)

In [ ]:
LabourForce_Current = LabourForce_Current_DateDroped.copy()

### Combine datasets

In [ ]:
LabourForce_Current.columns

In [ ]:
EmployPopulationRatial.columns

## Archive Codes

### Employment to population Ration

#### Observe and Analyse the dataset

In [ ]:
EmployPopulationRatial_Original

In [ ]:
EmployPopulationRatial = EmployPopulationRatial_Original.copy()

Observation:\
The size of the data set is 124X1. The only column is named Employment-to-population ratio. Under the column there are three sub-columns. The first column is datetime, and the rest are the numerical data. The last two rows are not the value of the datasets.

#### Data processing plan

Step1 - reset index and the column names.\
Step2 - remove the last two rows.\
Step3 - extract month and year.\
Step4 - convert the datatypes of month and year to numeric.\
Step5 - convert data in seasonally adjusted from percentage to decimal

#### Step1 - reset index and the column names.

In [ ]:
EmployPopulationRatial_ResetIndex = EmployPopulationRatial.reset_index()

In [ ]:
EmployPopulationRatial_ResetColumnName = EmployPopulationRatial_ResetIndex.copy()
EmployPopulationRatial_ResetColumnName.columns = EmployPopulationRatial_ResetColumnName.iloc[0].tolist()
EmployPopulationRatial_ResetColumnName = EmployPopulationRatial_ResetColumnName.iloc[1:]

In [ ]:
OriginalColumnNames = EmployPopulationRatial_ResetColumnName.columns
EmployPopulationRatial_ResetColumnName = EmployPopulationRatial_ResetColumnName.rename(columns = {OriginalColumnNames[0]:'Date', OriginalColumnNames[1]:'Employment_Population_Ratio', OriginalColumnNames[2]:'Ratio_SeasonallyAdjusted'})

In [ ]:
EmployPopulationRatial_ResetColumnName.head()

#### Step2 - remove the last two rows.

In [ ]:
EmployPopulationRatial_RemovedRows = EmployPopulationRatial_ResetColumnName.iloc[:121] 
EmployPopulationRatial_RemovedRows

#### Step3 - extract month and year.

In [ ]:
EmployPopulationRatial_ExtractMonthYear = EmployPopulationRatial_RemovedRows.copy()

In [ ]:
MonthYear = EmployPopulationRatial_ExtractMonthYear['Date'].str.split('-', expand=True)

In [ ]:
MonthYear.columns

In [ ]:
EmployPopulationRatial_ExtractMonthYear['Month_Name'] = MonthYear[0]
EmployPopulationRatial_ExtractMonthYear['Year'] = '20' + MonthYear[1]

In [ ]:
EmployPopulationRatial_ExtractMonthYear['Month'] = pd.to_datetime(EmployPopulationRatial_ExtractMonthYear['Month_Name'], format='%b').dt.month

In [ ]:
# drop Date, Month_Name
EmployPopulationRatial = EmployPopulationRatial_ExtractMonthYear.drop(columns = ['Date', 'Month_Name'])

In [ ]:
EmployPopulationRatial.head()

#### Step4 - convert the datatypes of month and year to numeric.

In [ ]:
EmployPopulationRatial['Year'] = EmployPopulationRatial['Year'].astype(int)

In [ ]:
EmployPopulationRatial['Month'] = EmployPopulationRatial['Month'].astype(int)

#### Step5 - convert data in seasonally adjusted from percentage to decimal

In [ ]:
#convert string to float then transfrom the data
EmployPopulationRatial['Ratio_SeasonallyAdjusted'] = EmployPopulationRatial['Ratio_SeasonallyAdjusted'].astype(float)/100

In [ ]:
#drop first column
EmployPopulationRatial_cleaned = EmployPopulationRatial[['Ratio_SeasonallyAdjusted', 'Year', 'Month']]

In [ ]:
EmployPopulationRatial_cleaned.head(5)

### CPI_MonthlyPath(Archive)

#### Observe and Analyse the dataset

In [ ]:
CPI_MonthlyPath = CPI_MonthlyOriginal.copy()
CPI_MonthlyPath.head()

Observation:\
Data set type - structural data, wide data sets
Size - 30rows X 133 columns
columns- first column contains the information of each rows without a column name which suppose to be the column names, including but not limited to Unit, series type, data type, etc. From the seconde column to the last column, the column name contains the industry, including all groups, non-alcoholic beverages, bread and cereal product, etc. 
Data types - the data sets contain categorical, numerical and datetime datasets

#### Data processing plan

Step1 - transfer the wide data to long.\
Step2 - extract the industries info and name the column industry.\
Step3 - extract the Month and Year information from the datetime (located in the first row originally), named as Month and Year.\
Step4 - deleted the columns/information that is not neceessary, for example colleciton month, series start, etc.\

#### Step1 - transfer the wide data to long.

In [ ]:
CPT_Wide = CPI_MonthlyPath.T

#### Step2 - extract the industries info and name the column industry.

In [ ]:
CPT_Wide.head()

In [ ]:
CPT_Wide_resetIndex = CPT_Wide.reset_index()

In [ ]:
CPT_Wide_resetIndex.head()

In [ ]:
#make first row as column name
CPT_Wide_resetIndex.columns = CPT_Wide_resetIndex.iloc[0]
CPT_DropFirstRow = CPT_Wide_resetIndex.drop(0, axis = 0)

In [ ]:
#name the first column industry
firstColumnName = CPT_DropFirstRow.columns[0]
rename = 'Industry'
CPT_rename = CPT_DropFirstRow.rename(columns = {firstColumnName:rename})

In [ ]:
#reset index
CPT_Wide_resetIndex = CPT_rename.reset_index(drop=True)

In [ ]:
#extract the industry
CPT_Wide_resetIndex['Industry'] = CPT_Wide_resetIndex['Industry'].str.split(' ; ', expand=True)[1]

#### Step3 - extract the Month and Year information from the datetime (located in the first row originally), named as Month and Year.

In [ ]:
CPT_Wide_resetIndex.columns[10:]

In [ ]:
#Get the columns that are not CPT with dates
CPT_nonDateColumnNames = CPT_Wide_resetIndex.columns[:10].tolist()
CPT_nonDateColumnNames

In [ ]:
#Melt the dataframe
CPT_MeltedDateTime = pd.melt(CPT_Wide_resetIndex, id_vars=CPT_nonDateColumnNames, var_name = 'DateTime', value_name = 'CPT_Changes')

In [ ]:
CPT_MeltedDateTime.head()

In [ ]:
CPT_MeltedDateTime.dtypes

In [ ]:
CPT_MeltedDateTime['Year'] = CPT_MeltedDateTime['DateTime'].dt.year

In [ ]:
CPT_MeltedDateTime['Month'] = CPT_MeltedDateTime['DateTime'].dt.month

In [ ]:
CPT_MeltedDateTime.head()

In [ ]:
CPT_MeltedDateTime.dtypes

#### Step4 - deleted the columns/information that is not neceessary, for example colleciton month, series start, etc.

In [ ]:
CPT = CPT_MeltedDateTime.copy()

In [ ]:
CPT['No. Obs'].unique()

Remove Unit, Series Type, Data Type, Frequency, Collection Month, No.Obs, because there is only one value in these columns

In [ ]:
dropedColumns = ['Unit', 'Series Type', 'Data Type', 'Frequency', 'Collection Month', 'No. Obs']

In [ ]:
CPT_DropedColumns = CPT.drop(columns = dropedColumns, axis = 1)

Also dropped Series Start, Series end and Series ID cause its not relavant to CPT changes. Dropped DateTime Cause we already have Year and Month

In [ ]:
dropedColumns = ['Series Start', 'Series End', 'DateTime', 'Series ID']

In [ ]:
CPT_DropedDates = CPT_DropedColumns.drop(columns = dropedColumns, axis = 1)

In [ ]:
CPT_DropedDates.shape

In [ ]:
CPT = CPT_DropedDates.copy()